import "./globals.css";
import Navigation from "./components/Navigation";
import { inter } from "./fonts";

export const metadata = {
  title: "Next.js App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${inter.className} box-border mx-auto px-28 py-10`}>
        <Navigation />
        {children}
      </body>
    </html>
  );
}
